CARLA_CONFIG:
  NUM_OF_VEHICLES: 0
  NUM_OF_WALKERS: 0

AGENT_CONFIG:
  # TRANSFORM: {location: [2, 13.5, 0.5], rotation: [0, 270, 0]}
  # TRANSFORM: {location: [1.8, -23.3, 0.5], rotation: [0, 270, 0]}
  # TRANSFORM: {location: [-369, 9.3, 0.5], rotation: [0, 250, 0]}
  TRANSFORM: {location: [97.7, -93.9, 2.5], rotation: [0, 180, 0]}
  BLUEPRINT: vehicle.lincoln.*

SENSOR_CONFIG:
  RGB:
    TRANSFORM: {location: [0, 0, 1.6], rotation: [0, 0, 0]}
    BLUEPRINT: sensor.camera.rgb
    ATTRIBUTE: {image_size_x: 1242, image_size_y: 375, fov: 90}

  DEPTH_RGB:
    TRANSFORM: { location: [ 0, 0, 1.6 ], rotation: [ 0, 0, 0 ] }
    BLUEPRINT: sensor.camera.depth
    ATTRIBUTE: { image_size_x: 1242, image_size_y: 375, fov: 180 }

  LIDAR:
    TRANSFORM: { location: [ 0, 0, 1.6 ], rotation: [ 0, 0, 0 ] }
    BLUEPRINT: sensor.lidar.ray_cast
    ATTRIBUTE: {range: 40, rotation_frequency: 20, lower_fov: -45, points_per_second: 1280000, channels: 64}
  
  SEMANTIC:
    TRANSFORM: {location: [0, 0, 50], rotation: [-90, 0, 0]}
    BLUEPRINT: sensor.camera.semantic_segmentation
    ATTRIBUTE: {image_size_x: 640, image_size_y: 640, fov: 90}

FILTER_CONFIG:
  PRELIMINARY_FILTER_DISTANCE: 40
  MAX_RENDER_DEPTH_IN_METERS: 50
  MIN_VISIBLE_VERTICES_FOR_RENDER: 3
  MAX_OUT_VERTICES_FOR_RENDER: 5

SAVE_CONFIG:
  ROOT_PATH: kitti_dataset
  STEP: 3